### ISSUE TITLE
本体和 Lyric Getter 版本不一致导致的无歌词显示

### ISSUE THREAD

**Issue by MisaLiu** [Block-Network/StatusBarLyric#389]
## 日志

```
----part 2 start----
[ 2023-11-05T19:43:48.590    10146: 13537: 13537 I/LSPosed-Bridge  ] Loading legacy module cn.lyric.getter from /data/app/~~VygjRVwX3HhS15fMs7VKgQ==/cn.lyric.getter--0T6Hu6pvrq_k9f8xohSIw==/base.apk
[ 2023-11-05T19:43:48.601    10146: 13537: 13537 I/LSPosed-Bridge  ]   Loading class cn.lyric.getter.hook.MainHook
[ 2023-11-05T19:43:48.626    10146: 13537: 13537 I/LSPosed-Bridge  ] Loading legacy module statusbar.lyric from /data/app/~~tK3gq1uumsjWTqKAjnCeng==/statusbar.lyric-TweiSRNj-KZLNFONrzI4aA==/base.apk
[ 2023-11-05T19:43:48.628    10146: 13537: 13537 I/LSPosed-Bridge  ]   Loading class statusbar.lyric.hook.MainHook
[ 2023-11-05T19:43:48.875    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:43:56.302    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:44:05.162    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:44:21.692    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:44:24.591    10058: 13995: 13995 I/LSPosed-Bridge  ] Loading legacy module com.github.dan.NoStorageRestrict from /data/app/~~JACFI8WnFIOt7qsAvVIoHg==/com.github.dan.NoStorageRestrict-i9hlaj8xmTzz7uY1Yt-_XA==/base.apk
[ 2023-11-05T19:44:24.594    10058: 13995: 13995 I/LSPosed-Bridge  ]   Loading class com.github.dan.NoStorageRestrict.XposedInit
[ 2023-11-05T19:44:24.953    10068: 14056: 14056 I/LSPosed-Bridge  ] Loading legacy module com.github.dan.NoStorageRestrict from /data/app/~~JACFI8WnFIOt7qsAvVIoHg==/com.github.dan.NoStorageRestrict-i9hlaj8xmTzz7uY1Yt-_XA==/base.apk
[ 2023-11-05T19:44:24.956    10068: 14056: 14056 I/LSPosed-Bridge  ]   Loading class com.github.dan.NoStorageRestrict.XposedInit
[ 2023-11-05T19:44:27.942    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:44:33.202    10128: 14262: 14262 I/LSPosed-Bridge  ] Loading legacy module cc.aoeiuv020.iamnotdisabled.hook from /data/app/~~rVX8fdEQTZvoS6BENn_cEw==/cc.aoeiuv020.iamnotdisabled.hook-7f_2y8YZ2I53O-at_18Ttw==/base.apk
[ 2023-11-05T19:44:33.205    10128: 14262: 14262 I/LSPosed-Bridge  ]   Loading class cc.aoeiuv020.iamnotdisabled.hook.MainHook
[ 2023-11-05T19:44:33.207    10128: 14262: 14262 I/LSPosed-Bridge  ] initZygote: /data/app/~~rVX8fdEQTZvoS6BENn_cEw==/cc.aoeiuv020.iamnotdisabled.hook-7f_2y8YZ2I53O-at_18Ttw==/base.apk
[ 2023-11-05T19:44:33.258    10128: 14262: 14262 I/LSPosed-Bridge  ] handleLoadPackage: com.android.chrome
```

## 环境信息
* OS: PixelExperiencePlus TQ3A.230805.001 (Android 13)
* KernelSU: 11193
* Zygisk on KSU: 4-0.7.1 (89)
* LSPosed: 1.9.2 (7024)
* 状态栏歌词: 6.1.1 (204)

~~## 应该是有用的附件
[系统界面_13.zip](https://github.com/Block-Network/StatusBarLyric/files/13259496/_13.zip)~~

**Comment by MisaLiu** [comment]
debug 版本的日志：

```
----part 3 start----
[ 2023-11-05T19:54:20.929    10146: 23341: 23341 I/LSPosed-Bridge  ] Loading legacy module cn.lyric.getter from /data/app/~~VygjRVwX3HhS15fMs7VKgQ==/cn.lyric.getter--0T6Hu6pvrq_k9f8xohSIw==/base.apk
[ 2023-11-05T19:54:20.940    10146: 23341: 23341 I/LSPosed-Bridge  ]   Loading class cn.lyric.getter.hook.MainHook
[ 2023-11-05T19:54:20.966    10146: 23341: 23341 I/LSPosed-Bridge  ] Loading legacy module statusbar.lyric from /data/app/~~OpTY9MxIlGumRrq6OuiNUg==/statusbar.lyric-K6q5jhC4-xVgqYXiIWLavA==/base.apk
[ 2023-11-05T19:54:21.010    10146: 23341: 23341 I/LSPosed-Bridge  ]   Loading class statusbar.lyric.hook.MainHook
[ 2023-11-05T19:54:21.168    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:statusbar.lyric - 6.1.1(204[zh] *debug)
[ 2023-11-05T19:54:21.168    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:歌词模式
[ 2023-11-05T19:54:21.181    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:Init Hook
[ 2023-11-05T19:54:21.242    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:* 限制可见性更改
[ 2023-11-05T19:54:21.248    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:* 歌词反色方案:* 歌词反色方案
[ 2023-11-05T19:54:21.250    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:* 有歌词时自动隐藏通知图标
[ 2023-11-05T19:54:21.252    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:* 隐藏运营商
[ 2023-11-05T19:54:21.256    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:Hook成功:SystemUILyric
[ 2023-11-05T19:54:26.669    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:Lyric Init
[ 2023-11-05T19:54:26.677    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:Change Config
[ 2023-11-05T19:54:45.424     1000:  2300:  2521 I/LSPosed-Bridge  ] [ INFO] 11-05 19:54:45 (ZygoteArgsHook) @startViaZygote force mount data: 10182 com.tencent.mobileqq
[ 2023-11-05T19:54:45.549    10182: 23793: 23793 I/LSPosed-Bridge  ] Loading legacy module io.github.qauxv from /data/app/~~xFz143h_1sHE3GBhbZSuag==/io.github.qauxv-Ckl8gIhE-NdQpezmQddOow==/base.apk
[ 2023-11-05T19:54:45.622    10182: 23793: 23793 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-11-05T19:54:45.624    10182: 23793: 23793 I/LSPosed-Bridge  ] Loading legacy module com.fankes.tsbattery from /data/app/~~YKute-MAvAIwqNX5i_59xA==/com.fankes.tsbattery-rHDi45mBdSCRJ5ClVsH9eQ==/base.apk
[ 2023-11-05T19:54:45.649    10182: 23793: 23793 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-11-05T19:54:45.669    10182: 23793: 23793 I/LSPosed-Bridge  ] Loading legacy module me.kyuubiran.qqcleaner from /data/app/~~9AcyjeWEEG0wuQ2oc5CoxQ==/me.kyuubiran.qqcleaner-oRWMDMfoAf8QHH4zYT-SaQ==/base.apk
[ 2023-11-05T19:54:45.680    10182: 23793: 23793 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-11-05T19:54:49.731    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:54:51.366     1000:  2300:  2521 I/LSPosed-Bridge  ] [ INFO] 11-05 19:54:51 (ZygoteArgsHook) @startViaZygote force mount data: 10182 com.tencent.mobileqq
[ 2023-11-05T19:54:51.518    10182: 23914: 23914 I/LSPosed-Bridge  ] Loading legacy module io.github.qauxv from /data/app/~~xFz143h_1sHE3GBhbZSuag==/io.github.qauxv-Ckl8gIhE-NdQpezmQddOow==/base.apk
[ 2023-11-05T19:54:51.597    10182: 23914: 23914 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-11-05T19:54:51.599    10182: 23914: 23914 I/LSPosed-Bridge  ] Loading legacy module com.fankes.tsbattery from /data/app/~~YKute-MAvAIwqNX5i_59xA==/com.fankes.tsbattery-rHDi45mBdSCRJ5ClVsH9eQ==/base.apk
[ 2023-11-05T19:54:51.627    10182: 23914: 23914 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-11-05T19:54:51.649    10182: 23914: 23914 I/LSPosed-Bridge  ] Loading legacy module me.kyuubiran.qqcleaner from /data/app/~~9AcyjeWEEG0wuQ2oc5CoxQ==/me.kyuubiran.qqcleaner-oRWMDMfoAf8QHH4zYT-SaQ==/base.apk
[ 2023-11-05T19:54:51.658    10182: 23914: 23914 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-11-05T19:54:57.393    10199:  8444:  8444 E/LSPosed-Bridge  ] a4.h: lateinit property sharedPreferences has not been initialized
	at z1.b.a(Unknown Source:29)
	at m4.a.a(Unknown Source:184)
	at s1.e.c(Unknown Source:48)
	at r1.b.a(Unknown Source:1268)
	at b2.a.afterHookedMethod(Unknown Source:11)
	at X.pWtVBW.FZ.mfSXmZTiSP.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.sendLyric(Unknown Source:46)
	at cn.lyric.getter.api.tools.EventTools.sendLyric(SourceFile:1)
	at androidx.core.j52.handleMessage(SourceFile:294)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
[ 2023-11-05T19:55:00.963    10182: 23914: 23914 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mobileqq] All processes are completed for "com.tencent.mobileqq"
[ 2023-11-05T19:55:01.399    10146: 23341: 23341 D/LSPosed-Bridge  ] StatusBarLyric:Hide Lyric
[ 2023-11-05T19:55:05.200    10182: 23793: 23793 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mobileqq] All processes are completed for "com.tencent.mobileqq:qzone"
[ 2023-11-05T19:58:59.008    10058: 28198: 28198 I/LSPosed-Bridge  ] Loading legacy module com.github.dan.NoStorageRestrict from /data/app/~~JACFI8WnFIOt7qsAvVIoHg==/com.github.dan.NoStorageRestrict-i9hlaj8xmTzz7uY1Yt-_XA==/base.apk
[ 2023-11-05T19:58:59.011    10058: 28198: 28198 I/LSPosed-Bridge  ]   Loading class com.github.dan.NoStorageRestrict.XposedInit
[ 2023-11-05T19:58:59.044     1000:  2300:  2521 I/LSPosed-Bridge  ] [ INFO] 11-05 19:58:59 (ZygoteArgsHook) @startViaZygote force mount data: 10307 com.cainiao.wireless
[ 2023-11-05T19:58:59.665    10068: 28326: 28326 I/LSPosed-Bridge  ] Loading legacy module com.github.dan.NoStorageRestrict from /data/app/~~JACFI8WnFIOt7qsAvVIoHg==/com.github.dan.NoStorageRestrict-i9hlaj8xmTzz7uY1Yt-_XA==/base.apk
[ 2023-11-05T19:58:59.667    10068: 28326: 28326 I/LSPosed-Bridge  ]   Loading class com.github.dan.NoStorageRestrict.XposedInit
```

**Comment by xiaowine** [comment]
@MisaLiu 并没有系统界面相关日志

**Comment by MisaLiu** [comment]
那我提供一下 LSPosed 导出的完整日志吧

[LSPosed_2023-11-05T19_44_24.431974.zip](https://github.com/Block-Network/StatusBarLyric/files/13277247/LSPosed_2023-11-05T19_44_24.431974.zip)

[LSPosed_2023-11-05T19_58_58.834795.zip](https://github.com/Block-Network/StatusBarLyric/files/13277249/LSPosed_2023-11-05T19_58_58.834795.zip)

**Comment by xiaowine** [comment]
@MisaLiu 你清理一下日志，重复下会出错的步骤

**Comment by MisaLiu** [comment]
(;¬_¬) 我把本体和 Lyric Getter 都卸载重新安装最新版之后就没有问题了，我猜测不显示歌词是由于本体和 Lyric Getter 版本不一致导致的

我觉得可以在本体里加一个当前使用的 Lyric Getter 版本的提示，如果不匹配就提醒用户更新（因为两大功能分开之后可能会出现像我这样的只更新一边的情况）

**Comment by xiaowine** [comment]
@MisaLiu 是有提示的

**Comment by MisaLiu** [comment]
> @MisaLiu 是有提示的

没有在本体里收到提示耶

**Comment by MisaLiu** [comment]
> @MisaLiu 说明是匹配的

🤔如果匹配的话那不应该会不显示歌词啊

怪起来了
