### ISSUE TITLE
HyperOS打开“隐藏运营商”后日志出现报错

### ISSUE THREAD

**Issue by klxiaoniu** [Block-Network/StatusBarLyric#405]
**Describe the bug**
-

**To Reproduce**
1.系统为HyperOS，安卓14；
2.打开“隐藏运营商”，并重启系统；
3.LSPosed日志中出现报错。

**Expected behavior**
无报错

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
 - Device: 红米K50
 - OS: HyperOS Android14
 - Version 6.1.2(205)

**Additional context**
日志：
[ 2023-12-30T15:32:08.539     1000:  3013:  3013 E/LSPosed-Bridge  ] java.lang.NoSuchFieldException: mCarrierLabel
	at java.lang.Class.getField(Class.java:2337)
	at d0.b.a(Unknown Source:560)
	at i.a.afterHookedMethod(Unknown Source:11)
	at PpYFGHED.S.P.urW.Yv.Lh.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.onFinishInflate(Unknown Source:8)
	at com.android.systemui.statusbar.phone.MiuiKeyguardStatusBarView.onFinishInflate(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1183)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1126)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1310)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1161)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1168)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1168)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1168)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1126)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1310)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1161)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1126)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get4(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:34)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:41)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get4(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:36)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:41)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get4(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:40)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:41)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get0(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:43)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:61)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get2(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:15)
[ 2023-12-30T15:32:08.539     1000:  3013:  3013 E/LSPosed-Bridge  ] 	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:51)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get7(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:95)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:26)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl.injectMiuiVendorServices(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:107)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl.-$$Nest$minjectMiuiVendorServices(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:1)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get8(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:82)
	at com.android.systemui.dagger.DaggerReferenceGlobalRootComponent$ReferenceSysUIComponentImpl$SwitchingProvider.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:21)
	at dagger.internal.DoubleCheck.get(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:14)
	at com.android.systemui.SystemUIApplication$$ExternalSyntheticLambda1.run(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:66)
	at com.android.systemui.SystemUIApplication.timeInitialization(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:28)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:18)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:6)
	at com.android.systemui.SystemUIService.onCreate(go/retraceme e32253fee68721f743148ad4e20b1172f209e7d0a1a4ffa9f598ca7baa64e59f:10)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4901)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2433)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

附上系统界面apk：
[系统界面_20230316.0(202303160).zip](https://github.com/Block-Network/StatusBarLyric/files/13797443/_20230316.0.202303160.zip)

**Comment by klxiaoniu** [comment]
补充：HyperOS的运营商位置为下拉控制中心后最右上角出现，应该不需要隐藏，只是我从MIUI升级过来保留了之前的配置，所以发现此报错
