### ISSUE TITLE
网易云生效问题，请求进一步排查

### ISSUE THREAD

**Issue by LTHPKBTE** [Block-Network/StatusBarLyric#446]
网易云内确认出现魅族状态栏选项，且确认测试模式可以显示模块名，但无法显示歌词
![Screenshot_2024-09-11-00-21-34-10_25d38497d72d75227633ae777c2e0df5](https://github.com/user-attachments/assets/9290be77-effe-4468-bb66-4d5e151d778b)
![Screenshot_2024-09-11-00-21-41-55_25d38497d72d75227633ae777c2e0df5](https://github.com/user-attachments/assets/61fd9430-d3ac-4c48-80f8-527d9ea744ce)
![Screenshot_2024-09-11-00-21-59-88_829ff6084417d749ddf938731682be03](https://github.com/user-attachments/assets/b7923a53-602b-421f-9a43-4a34286c2743)
![Screenshot_2024-09-11-00-22-12-72_f23e7e35f6987d1fc0492920c7cebf60](https://github.com/user-attachments/assets/a55424ce-1531-4b7b-91c8-0186bb35b376)
![Screenshot_2024-09-11-00-22-34-06_f23e7e35f6987d1fc0492920c7cebf60](https://github.com/user-attachments/assets/6fb6459e-30a2-4028-8f19-09f6599f09f5)
![Screenshot_2024-09-11-00-23-39-50_f23e7e35f6987d1fc0492920c7cebf60](https://github.com/user-attachments/assets/6facfa04-b676-4ec0-a939-59a9c6bb588d)

**Comment by LTHPKBTE** [comment]
墨-状态栏歌词
statusbar.lyric
Min 26 Target 34
版本 6.1.3(206)
首次安装时间 2024/06/11 16:11:46
最后更新时间 2024/06/11 16:11:46

酒域-歌词获取
cn.lyric.getter
Min 26 Target 34
版本 2.0.13(21)
首次安装时间 2024/06/11 16:10:07
最后更新时间 2024/09/11 00:37:05

网易云音乐
com.netease.cloudmusic
Min 28 Target 29
版本 8.9.20(8009020)
首次安装时间 2024/06/13 23:17:43
最后更新时间 2024/09/11 00:05:38

**Comment by LTHPKBTE** [comment]
能进一步排查的话请告知方法，谢谢

**Comment by LTHPKBTE** [comment]
经过测试，最新的墨-状态栏歌词(6.2.0)的显示标题打开蓝牙获取后可以显示标题，但是依旧无法显示歌词
且歌词获取应用会有随机崩溃报错:

AppErrorsTracking
[Device Brand]: OnePlus
[Device Model]: PJE110
[Display]: PJE110_14.0.0.800(CN01)
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 12283
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: cn.lyric.getter
[Version Name]: 2.0.13
[Version Code]: 21
[Target SDK]: 34
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-09-11T13:43:18.026
[Stack Trace]:
java.lang.IllegalArgumentException: Parcel: unknown type for value AppInfos(appName=Salt Player, appIcon=android.graphics.drawable.AdaptiveIconDrawable@eeb1d1c, packageName=com.salt.music, versionCode=2024072001, appRule=AppRule(packageName=com.salt.music, name=椒盐音乐, rules=[Rule(useApi=true, apiVersion=4, startVersionCode=2023071601, endVersionCode=2023081000, excludeVersions=[], getLyricType=0, remarks=), Rule(useApi=true, apiVersion=5, startVersionCode=2023081001, endVersionCode=2147483647, excludeVersions=[2023082301], getLyricType=0, remarks=), Rule(useApi=true, apiVersion=6, startVersionCode=2024021601, endVersionCode=2147483647, excludeVersions=[], getLyricType=0, remarks=), Rule(useApi=false, apiVersion=0, startVersionCode=2023010101, endVersionCode=2147483647, excludeVersions=[], getLyricType=0, remarks=)]), installed=true)
	at android.os.Parcel.getValueType(Parcel.java:2485)
	at android.os.Parcel.writeValue(Parcel.java:2384)
	at android.os.Parcel.writeList(Parcel.java:1445)
	at android.os.Parcel.writeValue(Parcel.java:2536)
	at android.os.Parcel.writeValue(Parcel.java:2392)
	at android.os.Parcel.writeList(Parcel.java:1445)
	at android.os.Parcel.writeValue(Parcel.java:2536)
	at android.os.Parcel.writeValue(Parcel.java:2392)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1328)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1397)
	at android.os.Parcel.writeValue(Parcel.java:2509)
	at android.os.Parcel.writeValue(Parcel.java:2399)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8848)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by YuKongA** [comment]
该问题为歌词获取问题，状态栏歌词 本体现在不负责这件事了。我们这边有空的话看看能不能复现。
