### ISSUE TITLE
6.5.0无法使用

### ISSUE THREAD

**Issue by phillaria** [Block-Network/StatusBarLyric#452]
安卓版本：11
机型：真我RMX2202(Realme GT)
lsposed版本：1.9.2(7024)
magisk版本：R65C33E4F-kitsune (27001)

更新后打开app闪退

**Comment by cmyyx** [comment]
同样遇到此问题
安卓12
黑鲨5P
lsposed: 1.9.2(7058)
magisk: alpha27007


FATAL EXCEPTION: main
Process: statusbar.lyric, PID: 18747
java.lang.VerifyError: Verifier rejected class sdwew.OoO08o: android.content.res.Resources sdwew.OoO08o.o000() failed to verify: android.content.res.Resources sdwew.OoO08o.o000(): [0x4]  can't resolve returned type 'Reference: android.content.res.Resources' or 'Unresolved Reference: android.content.res.XModuleResources' (declaration of 'sdwew.OoO08o' appears in base.apk)
	at sdwew.OoO08o.o0(Unknown Source:0)
	at sdwew.oOO〇.〇o(Unknown Source:17)
	at sdwew.o〇88.ooo〇0(Unknown Source:2)
	at statusbar.lyric.activity.SettingsActivity.onCreate(Unknown Source:9)
	at android.app.Activity.performCreate(Activity.java:8246)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1331)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3900)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8122)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
JUNK_FATAL_EXCEP: FATAL EXCEPTION: main,Process: statusbar.lyric, PID: 18747

**Comment by phillaria** [comment]
debug版可用

**Comment by cmyyx** [comment]
确实可用
