### ISSUE TITLE
造成系统界面崩溃

### ISSUE THREAD

**Issue by Adlyq** [Block-Network/StatusBarLyric#476]
**Describe the bug**
Android15 hyperos2
设置锚点后，播放音乐导致其崩溃，无歌词

```
[Device Brand]: Xiaomi
[Device Model]: 24129PN74C
[Display]: AQ3A.240812.002
[Android Version]: 15
[Android API Level]: 35
[System Locale]: zh_CN
[Process ID]: 25164
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20240808.0
[Version Code]: 202408080
[Target SDK]: 35
[Min SDK]: 35
[Error Type]: JVM
[Crash Time]: 2024-11-04T16:24:27.493
[Stack Trace]:
F1.s: lateinit property sharedPreferences has not been initialized
	at O0.b.a(Unknown Source:26)
	at C0.a.u(Unknown Source:24)
	at F0.b.onMetadataChanged(Unknown Source:10)
	at android.media.session.MediaController$MessageHandler.handleMessage(MediaController.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by xiaowine** [comment]
lsp没有正确激活导致的
